version: '3.9'

services:
  php-rest-db:
    image: mysql:8.4.0
    container_name: php-rest-db
    restart: unless-stopped
    hostname: php-rest-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'php-rest-api'
      MYSQL_USER: 'php-rest-api'
      MYSQL_PASSWORD: 'php-rest-api'
      MYSQL_ROOT_PASSWORD: '1lPDxsv4!'